create table hma.api_configuration (
    config_name  varchar2(100 byte) not null enable,
    config_value varchar2(1000 byte) not null enable
);

alter table hma.api_configuration
    add constraint pk_api_configuration primary key ( config_name )
        using index enable;


-- sqlcl_snapshot {"hash":"ac513fe8febc15aae817a45087df10f0b422628a","type":"TABLE","name":"API_CONFIGURATION","schemaName":"HMA","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>HMA</SCHEMA><NAME>API_CONFIGURATION</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>CONFIG_NAME</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>100</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME><NOT_NULL></NOT_NULL></COL_LIST_ITEM><COL_LIST_ITEM><NAME>CONFIG_VALUE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>1000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME><NOT_NULL></NOT_NULL></COL_LIST_ITEM></COL_LIST><PRIMARY_KEY_CONSTRAINT_LIST><PRIMARY_KEY_CONSTRAINT_LIST_ITEM><NAME>PK_API_CONFIGURATION</NAME><COL_LIST><COL_LIST_ITEM><NAME>CONFIG_NAME</NAME></COL_LIST_ITEM></COL_LIST><USING_INDEX></USING_INDEX></PRIMARY_KEY_CONSTRAINT_LIST_ITEM></PRIMARY_KEY_CONSTRAINT_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}