create table hma.app_settings (
    setting_name  varchar2(100 byte) not null enable,
    setting_value varchar2(1000 byte) not null enable
);

alter table hma.app_settings
    add constraint pk_app_settings primary key ( setting_name )
        using index enable;


-- sqlcl_snapshot {"hash":"f84cd761dedbe547576a099f50085aef8cd22b07","type":"TABLE","name":"APP_SETTINGS","schemaName":"HMA","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>HMA</SCHEMA><NAME>APP_SETTINGS</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>SETTING_NAME</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>100</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME><NOT_NULL></NOT_NULL></COL_LIST_ITEM><COL_LIST_ITEM><NAME>SETTING_VALUE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>1000</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME><NOT_NULL></NOT_NULL></COL_LIST_ITEM></COL_LIST><PRIMARY_KEY_CONSTRAINT_LIST><PRIMARY_KEY_CONSTRAINT_LIST_ITEM><NAME>PK_APP_SETTINGS</NAME><COL_LIST><COL_LIST_ITEM><NAME>SETTING_NAME</NAME></COL_LIST_ITEM></COL_LIST><USING_INDEX></USING_INDEX></PRIMARY_KEY_CONSTRAINT_LIST_ITEM></PRIMARY_KEY_CONSTRAINT_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}